---
- name: Get the latest node_exporter version
  uri:
    url: "https://api.github.com/repos/prometheus/node_exporter/releases/latest"
    return_content: yes
  register: node_exporter_release_data

- name: Set node_exporter_version to the latest
  set_fact:
    node_exporter_version: "{{ node_exporter_release_data.json.tag_name }}"
